modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Cable-Tiers/issues/new/choose"
[[mods]]
modId="cabletiers"
version="${file.jarVersion}"
displayName="Cable Tiers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cable-tiers"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds better Importer, Exporter, Constructor, Destructor, Disk Manipulator, Requester from Refined Storage and RSRequestify."

[[dependencies.cabletiers]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
